<=======================================[ShowInfo: ]=======================================>
Table
{
    1 =
    {
        itemName = GEM,
        itemType = 4,
        id = 93580,
        sortId = 0,
        count = 0,
        position = 0,
        name = 123580,
        level = 1,
        icon = piece/nfy_gem_icon/ui_baoshi_yuan_fen_kuangbaoyingwang.png,
        quality = 450,
    },
    2 =
    {
        itemName = GEM,
        itemType = 4,
        id = 93570,
        sortId = 0,
        count = 0,
        position = 0,
        name = 123570,
        level = 1,
        icon = piece/nfy_gem_icon/ui_baoshi_yuan_fen_miusi.png,
        quality = 450,
    },
    3 =
    {
        itemName = GEM,
        itemType = 4,
        id = 93560,
        sortId = 0,
        count = 0,
        position = 0,
        name = 123560,
        level = 1,
        icon = piece/nfy_gem_icon/ui_baoshi_yuan_fen_lian.png,
        quality = 450,
    },
    4 =
    {
        itemName = GEM,
        itemType = 4,
        id = 93550,
        sortId = 0,
        count = 0,
        position = 0,
        name = 123550,
        level = 1,
        icon = piece/nfy_gem_icon/ui_baoshi_yuan_fen_yinglie.png,
        quality = 450,
    },
    5 =
    {
        itemName = GEM,
        itemType = 4,
        id = 93540,
        sortId = 0,
        count = 0,
        position = 0,
        name = 123540,
        level = 1,
        icon = piece/nfy_gem_icon/ui_baoshi_yuan_fen_leiya.png,
        quality = 450,
    },
    6 =
    {
        itemName = GEM,
        itemType = 4,
        id = 93530,
        sortId = 0,
        count = 0,
        position = 0,
        name = 123530,
        level = 1,
        icon = piece/nfy_gem_icon/ui_baoshi_yuan_fen_yingwang.png,
        quality = 450,
    },
    7 =
    {
        itemName = GEM,
        itemType = 4,
        id = 93520,
        sortId = 0,
        count = 0,
        position = 0,
        name = 123520,
        level = 1,
        icon = piece/nfy_gem_icon/ui_baoshi_yuan_fen_yangui.png,
        quality = 450,
    },
    8 =
    {
        itemName = GEM,
        itemType = 4,
        id = 93410,
        sortId = 0,
        count = 0,
        position = 0,
        name = 123410,
        level = 1,
        icon = piece/nfy_gem_icon/ui_baoshi_yuan_fen_shengming.png,
        quality = 450,
    },
    9 =
    {
        itemName = GEM,
        itemType = 4,
        id = 92580,
        sortId = 0,
        count = 0,
        position = 0,
        name = 122580,
        level = 1,
        icon = piece/nfy_gem_icon/ui_baoshi_fang_fen_yunjin.png,
        quality = 450,
    },
    10 =
    {
        itemName = GEM,
        itemType = 4,
        id = 92570,
        sortId = 0,
        count = 0,
        position = 0,
        name = 122570,
        level = 1,
        icon = piece/nfy_gem_icon/ui_baoshi_fang_fen_may.png,
        quality = 450,
    },
    11 =
    {
        itemName = GEM,
        itemType = 4,
        id = 92560,
        sortId = 0,
        count = 0,
        position = 0,
        name = 122560,
        level = 1,
        icon = piece/nfy_gem_icon/ui_baoshi_fang_fen_ciyuanxianfeng.png,
        quality = 450,
    },
    12 =
    {
        itemName = GEM,
        itemType = 4,
        id = 92550,
        sortId = 0,
        count = 0,
        position = 0,
        name = 122550,
        level = 1,
        icon = piece/nfy_gem_icon/ui_baoshi_fang_fen_hundunshikongshou.png,
        quality = 450,
    },
    13 =
    {
        itemName = GEM,
        itemType = 4,
        id = 92540,
        sortId = 0,
        count = 0,
        position = 0,
        name = 122540,
        level = 1,
        icon = piece/nfy_gem_icon/ui_baoshi_fang_fen_suolasit.png,
        quality = 450,
    },
    14 =
    {
        itemName = GEM,
        itemType = 4,
        id = 92430,
        sortId = 0,
        count = 0,
        position = 0,
        name = 122430,
        level = 1,
        icon = piece/nfy_gem_icon/ui_baoshi_fang_fen_baokang.png,
        quality = 450,
    },
    15 =
    {
        itemName = GEM,
        itemType = 4,
        id = 92420,
        sortId = 0,
        count = 0,
        position = 0,
        name = 122420,
        level = 1,
        icon = piece/nfy_gem_icon/ui_baoshi_fang_fen_mofafangyu.png,
        quality = 450,
    },
    16 =
    {
        itemName = GEM,
        itemType = 4,
        id = 92410,
        sortId = 0,
        count = 0,
        position = 0,
        name = 122410,
        level = 1,
        icon = piece/nfy_gem_icon/ui_baoshi_fang_fen_wulifangyu.png,
        quality = 450,
    },
    17 =
    {
        itemName = GEM,
        itemType = 4,
        id = 91580,
        sortId = 0,
        count = 0,
        position = 0,
        name = 121580,
        level = 1,
        icon = piece/nfy_gem_icon/ui_baoshi_sanjiao_fen_dakaer.png,
        quality = 450,
    },
    18 =
    {
        itemName = GEM,
        itemType = 4,
        id = 91570,
        sortId = 0,
        count = 0,
        position = 0,
        name = 121570,
        level = 1,
        icon = piece/nfy_gem_icon/ui_baoshi_sanjiao_fen_jidaoke.png,
        quality = 450,
    },
    19 =
    {
        itemName = GEM,
        itemType = 4,
        id = 91560,
        sortId = 0,
        count = 0,
        position = 0,
        name = 121560,
        level = 1,
        icon = piece/nfy_gem_icon/ui_baoshi_sanjiao_fen_shaye.png,
        quality = 450,
    },
    20 =
    {
        itemName = GEM,
        itemType = 4,
        id = 91550,
        sortId = 0,
        count = 0,
        position = 0,
        name = 121550,
        level = 1,
        icon = piece/nfy_gem_icon/ui_baoshi_sanjiao_fen_yeyuan.png,
        quality = 450,
    },
    21 =
    {
        itemName = GEM,
        itemType = 4,
        id = 91440,
        sortId = 0,
        count = 0,
        position = 0,
        name = 121440,
        level = 1,
        icon = piece/nfy_gem_icon/ui_baoshi_sanjiao_fen_baoshang.png,
        quality = 450,
    },
    22 =
    {
        itemName = GEM,
        itemType = 4,
        id = 91430,
        sortId = 0,
        count = 0,
        position = 0,
        name = 121430,
        level = 1,
        icon = piece/nfy_gem_icon/ui_baoshi_sanjiao_fen_baoji.png,
        quality = 450,
    },
    23 =
    {
        itemName = GEM,
        itemType = 4,
        id = 91420,
        sortId = 0,
        count = 0,
        position = 0,
        name = 121420,
        level = 1,
        icon = piece/nfy_gem_icon/ui_baoshi_sanjiao_fen_mogong.png,
        quality = 450,
    },
    24 =
    {
        itemName = GEM,
        itemType = 4,
        id = 91410,
        sortId = 0,
        count = 0,
        position = 0,
        name = 121410,
        level = 1,
        icon = piece/nfy_gem_icon/ui_baoshi_sanjiao_fen_wugong.png,
        quality = 450,
    },
}